### ISSUE TITLE
Waiting type don't change on 

### ISSUE THREAD

**Issue by jotafe** [InfotelGLPI/moreticket#10]
I use the Waiting type view on defaults intens to show, and apear only the first type used even if I select another type later.

I use GLPI 0.90 and moreticket 1.2.2

**Comment by tsmr** [comment]
Can you add screenshots please ?

**Comment by jotafe** [comment]
here you  can see the last type is "aguardando usuário"
![glpi_moreticket](https://cloud.githubusercontent.com/assets/15238629/12300250/c72ca46a-ba01-11e5-8040-e090ebd3af6f.png)

But On general view the type is "aguardando fornecedor" the first type that I used
![glpi_moreticket2](https://cloud.githubusercontent.com/assets/15238629/12300251/c742c4de-ba01-11e5-8085-04d2f519b16a.png)
