### ISSUE TITLE
[GLPI 10] [Moreticket 1.7.0] Can't select waiting ticket reason

### ISSUE THREAD

**Issue by jgrunder** [InfotelGLPI/moreticket#101]
* Version of the plugin : 1.7.0

* Version of your GLPI : 10.0.0

* Steps to reproduce (which actions have you made) : Try to put a ticket in "waiting" status but I can't give a reason nor a description

* Expected result : Should have 2 more input, a text input and a select box

* Actual result : None appear

* URL of the page : Internal

* Note : this is an upgrade GLPI from 9.5 to 10.0 and I removed the plugin and reinstall it but no change

* Screenshot of the problem (if pertinent) :
![2022-05-06_08h15_42](https://user-images.githubusercontent.com/59175963/167077359-d3fbc112-951f-4f9c-8ffd-6db794a4e4c1.png)
![2022-05-06_08h15_58](https://user-images.githubusercontent.com/59175963/167077378-2087ccb6-35b5-409b-b8ab-b9ed6ac4ef13.png)

**Comment by jcovillers78114** [comment]
Same for me

**Comment by tsmr** [comment]
This option is directly into GLPI now. So this is not a bug of the plugin. You can open a ticket into GLPI project. I close

**Comment by jgrunder** [comment]
OK please add this in your doc as you still say it's an available option for last version of GLPI
