### ISSUE TITLE
[GLPI9.5.7][moreticket 1.6.1]

### ISSUE THREAD

**Issue by hcimadomo-procsi** [InfotelGLPI/moreticket#102]
Hello,
when i activate the plugin, the view of task lose the time of task:
* Expected result :
![image](https://user-images.githubusercontent.com/103555535/169003738-1c1a3acf-8ca0-4517-9f38-d1f571578c15.png)
* Actual result :
![image](https://user-images.githubusercontent.com/103555535/169004202-a3c5a052-aa1a-44f4-b254-9e61ce2afc1c.png)

How resolv it please ?
Best regards

**Comment by tsmr** [comment]
Verify your profile

![image](https://user-images.githubusercontent.com/13178158/169051255-a40ac580-5864-48b4-8f31-0b0ebd73a386.png)

**Comment by tsmr** [comment]
Old issue - use GLPI10 - i close
