### ISSUE TITLE
Pending date not update

### ISSUE THREAD

**Issue by SilvaFernando** [InfotelGLPI/moreticket#103]
Dear GLPi user.

BEFORE SUBMITTING YOUR ISSUE, please make sure to read and follow these steps :

* Verify that your question has not already been asked
* Please use the below template.
* Delete this text before submiting your issue.

The Plugin team.

------------
* Version of the plugin : 
1.6.1

* Version of your GLPI : 
9.5.7

* Steps to reproduce (which actions have you made) :
Pending date not update 

* Expected result :
Alter pending date from ticket

* Actual result :
when i add a pending status for a day 05/08/2022 and i update from another day ex: 09/08/2022, in my personal vision the date continue 05/08/2022

* Screenshot of the problem (if pertinent) :
* 
<img width="206" alt="image" src="https://user-images.githubusercontent.com/53239752/183096554-20771213-4b1c-4fc2-aa53-ab75512e0e3b.png">

<img width="80" alt="image" src="https://user-images.githubusercontent.com/53239752/183096701-2d0c6be5-0a16-4ef3-9969-53603e54b419.png">

**Comment by tsmr** [comment]
Old issue - use GLPI10 - i close
