### ISSUE TITLE
GLPI 10.0.2 : plus de zone de justification de mise en attente

### ISSUE THREAD

**Issue by Sicoval31** [InfotelGLPI/moreticket#104]
GLPI 10.0.X (linux ou windows)
Plugin 1.7.1
---
Les options "ticket en attente" ont disparues dans la configuration du plugin et donc lors de la mise en attente d'un ticket afin d'afficher la justification

Ok avec GLPI 9.5.7 et plugin 1.6.1

**Comment by imanou10** [comment]
Oui c'est dommage c'était très pratique

**Comment by Acs2i** [comment]
Cette fonctionnalité va être réimplémentée ?
Sans cela, nous ne pouvons migrer en v10 :(

**Comment by M-Falken** [comment]
Same as above, mandatory feature should be relocated.

**Comment by Sicoval31** [comment]
Idem avec glpi 10.0.3.
Si cette option à disparue du plugin, merci de mettre à jour le descriptif, c'est l'un des intérêt majeur de ce plugin

**Comment by Sicoval31** [comment]
2 mois plus tard ... des news sur cette fonctionnalité disparue ?

**Comment by Sicoval31** [comment]
je comprends tout à fait ce point de vue sur l'open source.
Merci pour cette réponse, attendue.
Moins sure la démarche commerciale qui consiste à proposer dans un premier temps un outil avec des options qui deviennent payantes si elles sont plébiscitées. Si cela n'etait pas la volonté première, en tout cas c'est le ressenti final ;).

Du coup, je vais le désinstaller, ne cautionnant pas cette pratique peu honorable.

Namasté
_(un nem offert)_

**Comment by tsmr** [comment]
Ce n'est pas du tout le but (devenir payant). C'est juste que le coeur de glpi, gère maintenant les types d'attentes, donc la fonctionnalité a été enlevé. De ce fait, soit pour accélérer la remise en marche de la fonctionnalité, on passe par un développement complémentaire, soit de notre propre chef, nous passons du temps à remettre en place la fonctionnalité, mais la patience est de mise..

**Comment by Sicoval31** [comment]
Merci pour cet éclaircissement :)

**Comment by tsmr** [comment]
https://github.com/InfotelGLPI/moreticket/releases/tag/1.7.2
