### ISSUE TITLE
Migration of column "glpi_plugin_moreticket_urgencytickets.tickets_id" cannot be done as it is referenced in CONSTRAINT "glpi_plugin_moreticket_urgencytickets_ibfk_1" of table "glpi_plugin_moreticket_urgencytickets.tickets_id".

### ISSUE THREAD

**Issue by Sicoval31** [InfotelGLPI/moreticket#105]
Bonjour, 
lors de la migration des colonnns des tables avec la commande console **glpi:migration:unsigned_keys** j'ai les deux erreurs suivantes : 
**Migration of column "glpi_plugin_moreticket_urgencytickets.tickets_id" cannot be done as it is referenced in CONSTRAINT "glpi_plugin_moreticket_urgencytickets_ibfk_1" of table "glpi_plugin_moreticket_urgencytickets.tickets_id".

Migration of column "glpi_tickets.id" cannot be done as it is referenced in CONSTRAINT "glpi_plugin_moreticket_urgencytickets_ibfk_1" of table "glpi_plugin_moreticket_urgencytickets.tickets_id".**

Quelle script passer sous mysql (mysqlworkbench) ou autre manipulation pour rétablir la situation ?

**Comment by tsmr** [comment]
Do this
ALTER TABLE `glpi_plugin_moreticket_urgencytickets` DROP FOREIGN KEY glpi_plugin_moreticket_urgencytickets_ibfk_1;

**Comment by NazarovRoman** [comment]
Thanks - that helped!! You are the best!
