### ISSUE TITLE
GLPI 9.5.7 - Activation Not Working ?

### ISSUE THREAD

**Issue by Mawuena** [InfotelGLPI/moreticket#106]
Dear GLPi user.

BEFORE SUBMITTING YOUR ISSUE, please make sure to read and follow these steps :

* Verify that your question has not already been asked
* Please use the below template.
* Delete this text before submiting your issue.

The Plugin team.

------------
* Version of the plugin : 1.6.1

* Version of your GLPI : 9.5.7

* Steps to reproduce (which actions have you made) :
* Activate and then going into "follow up" or "task" or "ticket" and nothing is showing in the status as having more

* Expected result :
* To have more options show up

* Actual result :
* To have more options show up and have an activation working

* URL of the page : vts.vejes.com

* Screenshot of the problem (if pertinent) :
See attached
![More Ticket Configuration](https://user-images.githubusercontent.com/840190/192269071-8354919c-ed2c-492b-852a-1dfc7062f0fd.PNG)

![Status](https://user-images.githubusercontent.com/840190/192269083-9db3c706-7165-4708-bf16-8875286e8ba6.PNG)

Profile Configuration for all profile
![image](https://user-images.githubusercontent.com/840190/192290445-c6e5ef49-f661-4f73-927f-3622ce0692f7.png)

**Comment by Mawuena** [comment]
Now we are using it more and we see that it's indicating some error messages as if it's active

For putting ticket on pending
![image](https://user-images.githubusercontent.com/840190/192289955-0d9fdad8-d647-4e6f-8443-50f936bd79a7.png)

For resolving ticket
![image](https://user-images.githubusercontent.com/840190/192290022-262987c0-8fbd-4a54-9379-11d7465393de.png)


However when we try to put ticket on pending through follow up or task or even the ticket => no additional field show up
Same for resolving => no additional field show up

Any idea?

**Comment by Mawuena** [comment]
HEllo

Any ideas for this one please ?

Sincerely,

Mawuena

**Comment by Mawuena** [comment]
HEllo

Any ideas for this one please ?

Sincerely,

Mawuena

**Comment by tsmr** [comment]
Old issue - use GLPI10 - i close
