### ISSUE TITLE
[GLPI 10.0.3] la zone de clôture n'apparaît pas à la création d'un ticket

### ISSUE THREAD

**Issue by sebfun** [InfotelGLPI/moreticket#107]
Bonjour à tous
Je viens de tester avec la dernière version de GLPI et de more ticket mais cela ne fonctionne pas, il n'y a pas de cadre pour saisir un message de clôture
Merci d'avance
------------
* Version of the plugin : 1.7.1

* Version of your GLPI : 10.0.3

* Steps to reproduce (which actions have you made) :
Setup plugin with closed and solved tags defined
create a new ticket with closed statut

* Expected result :
Ability to close a created ticket with closed message (in 1 step)

* Actual result :
It creates the ticket with closed statut but I'm not able to write a closed message

* URL of the page :
intranet page

* Screenshot of the problem (if pertinent) :
![image](https://user-images.githubusercontent.com/15892696/197737393-f61110dc-3714-41d8-bb85-0edd11b2b541.png)

**Comment by tsmr** [comment]
Have you define this ?
![image](https://user-images.githubusercontent.com/13178158/197749161-bb609765-c384-4c47-84d0-8beca3555ced.png)

**Comment by sebfun** [comment]
Yes I have

**Comment by damien51** [comment]
same here.

**Comment by tsmr** [comment]
https://github.com/InfotelGLPI/moreticket/releases/tag/1.7.2
