### ISSUE TITLE
White screen when opening a new ticket

### ISSUE THREAD

**Issue by serviceticst** [InfotelGLPI/moreticket#108]
Dear GLPi user.

BEFORE SUBMITTING YOUR ISSUE, please make sure to read and follow these steps :

* Verify that your question has not already been asked
* Please use the below template.
* Delete this text before submiting your issue.

The Plugin team.

------------
* Version of the plugin : 1.7.1

* Version of your GLPI : 10.0.3

* Steps to reproduce (which actions have you made) :  Administration > New Call

* Expected result : open call

* Actual result : White screen

* URL of the page : https://canal.servicetic.com.br/ 

* Screenshot of the problem (if pertinent) :

when creating a new ticket on a fresh install of GLPI 10.0.3, the screen goes white, when deactivating the plugin, glpi opens the normal ticket.

![image](https://user-images.githubusercontent.com/70910492/198847711-32f37e8e-18ac-431e-be3d-426a01405c94.png)

![image](https://user-images.githubusercontent.com/70910492/198847724-00fd5596-5c9d-45b5-991c-6723988d32e4.png)

![image](https://user-images.githubusercontent.com/70910492/198847837-d9f81af7-159d-4a52-88a5-4f9278119d42.png)

with the plugin disabled

![image](https://user-images.githubusercontent.com/70910492/198847861-c3a760a7-b04c-47a4-9c79-5bb0f5e0852c.png)

![image](https://user-images.githubusercontent.com/70910492/198847873-3e3b7e58-473f-4b53-8496-ec89b09a7bab.png)

**Comment by tsmr** [comment]
Hello - any errors in debug mode ?

**Comment by serviceticst** [comment]
![image](https://user-images.githubusercontent.com/70910492/199250055-a043c4c6-848b-476e-a4d8-543299336ca2.png)
