### ISSUE TITLE
Error un Upgrading do 1.7.1 - SQL Error

### ISSUE THREAD

**Issue by aferronato** [InfotelGLPI/moreticket#109]
------------
* Version of the plugin :  1.7.1

* Version of your GLPI :  10.0.5

* Steps to reproduce (which actions have you made) :
Upgrade moreticket to 1.7.1

* Expected result :
Upgrade the plugin without problems

* Actual result :
`SQL Error "1091": Can't DROP 'glpi_plugin_moreticket_notificationtickets_ibfk_1'; check that column/key exists in query "ALTER TABLE `glpi_plugin_moreticket_notificationtickets` DROP FOREIGN KEY glpi_plugin_moreticket_notificationtickets_ibfk_1"`

**Comment by grcamposdev** [comment]
Hello, I am also having problems updating the plugin in version 10.0.5.


alert: 

- 1 primary or foreign keys columns are using signed integers. Run the "php bin/console glpi:migration:unsigned_keys" command to migrate them.

after running the command

> php bin/console glpi:migration:unsigned_keys

Showing the following error.

Migration of column "glpi_plugin_moreticket_urgencytickets.tickets_id" cannot be done as it is referenced in CONSTRAINT "glpi_plugin_moreticket_urgencytickets_ibfk_1" of table "glpi_plugin_moreticket_urgencytickets.tickets_id".
Migration of column "glpi_tickets.id" cannot be done as it is referenced in CONSTRAINT "glpi_plugin_moreticket_urgencytickets_ibfk_1" of table "glpi_plugin_moreticket_urgencytickets.tickets_id".
 2/2 [============================] 100%
Errors occurred during migration.
Some errors are related to following plugins: Mais incidência.
You should try to update these plugins to their latest version and run the command again.


![image](https://user-images.githubusercontent.com/66086374/203115203-ff26bafd-e7a8-42b8-8faf-30e95c40ec76.png)

**Comment by M-Falken** [comment]
Hi
same issue for me

**Comment by M-Falken** [comment]
@tsmr Hi, No news on this one ?

**Comment by tsmr** [comment]
https://github.com/InfotelGLPI/moreticket/issues/105
