### ISSUE TITLE
bug on plugins page

### ISSUE THREAD

**Issue by lexx015** [InfotelGLPI/moreticket#11]
Hello!
Just updated from master branch and occurred an error with displaying plugin page, it is empty.
Also got an error

2016-01-20 17:32:08 [72@glpi]
  *** PHP Notice(8): Undefined index: close_followup
  Backtrace :
  plugins/moreticket/inc/config.class.php:132
  plugins/moreticket/front/config.form.php:49        PluginMoreticketConfig->showForm()

GLPI 0.90
PHP 5.6.14-0+deb8u1

**Comment by tsmr** [comment]
The plugin must be updated from plugins list ?

**Comment by lexx015** [comment]
Oh, this is my issue. I copied old version to the moreticket_bak folder. So this brings trouble with displaying plugin page.
