### ISSUE TITLE
 Cannot delete or update a parent row: a foreign key constraint fails (`glpidb`.`glpi_plugin_moreticket_urgencytickets`, CONSTRAINT `glpi_plugin_moreticket_urgencytickets_ibfk_1` FOREIGN KEY (`tickets_id`) REFERENCES `glpi_tickets` (`id`))

### ISSUE THREAD

**Issue by NazarovRoman** [InfotelGLPI/moreticket#110]
------------
* Version of the plugin :  1.7.1

* Version of your GLPI :  10.0.3 

* Steps to reproduce (which actions have you made) :

![image](https://user-images.githubusercontent.com/40058572/210940112-08a21bef-6403-41b5-8a2c-df5a931eb6bc.png)

* Expected result :

![image](https://user-images.githubusercontent.com/40058572/210940350-7cec2c97-77b5-4e38-b4b5-f7e333b2435a.png)

* Actual result :

* URL of the page :  https://help.bpmg.kz/

* Screenshot of the problem (if pertinent) :

Log:

![image](https://user-images.githubusercontent.com/40058572/210940747-02eb4087-c302-44df-a39a-34f30a8bd260.png)

**Comment by tsmr** [comment]
Fixed by https://github.com/InfotelGLPI/moreticket/issues/105#issuecomment-1373195045
