### ISSUE TITLE
Mettre un ticket en attente pour une durée prédéfinie

### ISSUE THREAD

**Issue by Dwarkin33** [InfotelGLPI/moreticket#113]
* Version of the plugin : 
More Ticket 1.71

* Version of your GLPI : 
GLPI 10.0.6

* Steps to reproduce (which actions have you made) :
Mettre un ticket en attente, et choisir une raison de mise en attente et une durée de mise en attente.

* Expected result :
Après échéance de la durée de mise en attente, le statut du ticket rebascule en "en cours" automatiquement.
Cela était possible dans la version précédente dont je disposais. C'était une fonctionnalité très pratique pour faire des relances, ou clôturer le ticket.

* Actual result :
Ne semble plus être possible.

**Comment by M-Falken** [comment]
Bonjour,
cette fonction fait maintenant partie intégrante de GLPI.
Vous devez d'abord définir vos raisons d'attentes : 
via > Configuration / Intitulés / Assistance / Raisons d'attentes
Vous pouvez alors également définir : 
- Fréquence des suivis automatiques 
- Suivis avant la résolution automatique
Du même coup vous pouvez alors assigner des templates qui seront utilisées lors des notifications déclenchées par les deux paramètres précédents.

Ensuite la mise en attente se fait maintenant par le biais des tâches.
Pour cela une fois la tâche ajoutée dans le fil du ticket, ou lors de sa modification, vous pouvez cochez le petit bouton en forme de pause juste à droite du bouton de suppression définitive.
Alors vous choisissez la raison d'attente souhaitée par le menu déroulant, les deux autres à droite permettent de définir les fréquences de notifications différentes de celles par défaut.,
