### ISSUE TITLE
petit bug avec GLPI 0.90 et moretickets 1.2.1

### ISSUE THREAD

**Issue by sebfun** [InfotelGLPI/moreticket#12]

**Comment by sebfun** [comment]
Bonjour,
Lorsque l'on choisi dans l'état clos ou résolu ou même un autre et qu'on a saisi du texte dans le champ de résolution et qu'on a oublié de renseigner un champ obligatoire (par exemple j'ai mis le champ catégorie en obligatoire), si on valide le formulaire se recharge reprend les champs renseignés sauf le champ texte de résolution qui est remis à zéro. En revanche la listbox où j'avais sélectionné Résolu reste dans le même état.

**Comment by tsmr** [comment]
Je n'ai pas ce comportement avec le master (1.2.2) Pouvez-vous mettre à jour le plugin avec le master.zip et videz votre cache et réessayer ?

**Comment by sebfun** [comment]
Faut-il que je désactive le plugin avant la mise à jour ?

**Comment by tsmr** [comment]
Non. Deplacez l'ancien répertoire vers un répertoire de sauvegarde type \glpi\plugins\old\moreticket
et ajouter le nouveau dans \glpi\plugins et lancez la MAJ

**Comment by sebfun** [comment]
ok j'ai fait ce que vous m'avez demandé mais le résultat est le même.

Je saisis tous les champs sauf Catégorie (que j'ai mis en obligatoire), je saisis dans le champ texte de la résolution, je valide le formulaire, la page se recharge et affiche tout.
Je complète ensuite en sélectionnant la catégorie, la page se recharge mais le champ texte de résolution est vide

**Comment by tsmr** [comment]
Oui je réplique. Ça ne garde pas les valeurs en cas de changement de type ou de catégorie de ticket.
A corriger donc
