### ISSUE TITLE
Complément zone "En attente" non visible 

### ISSUE THREAD

**Issue by Gilmor49** [InfotelGLPI/moreticket#15]
Bonjour,
les zones supplémentaires ne sont pas visibles si le profil utilisé n'est pas "Super Admin".
Il faudrait le rendre disponible pour le niveau technicien à minima.

Merci pour cette extension, elle facilite la gestion quotidienne.

Cdt, Gilles

**Comment by tsmr** [comment]
Avez-vous donné les droits sur les autres profils sur le plugin ?

**Comment by Gilmor49** [comment]
Bonjour,
merci pour votre réponse. Désolé, mais je ne vois pas à quel niveau associé ces droits?
Pouvez-vous m'éclairer?
Merci, Gilles

**Comment by tsmr** [comment]
Administration > profils - dans un profil technicien > Onglet MoreTicket

**Comment by Gilmor49** [comment]
Parfait.
Merci pour votre aide.

Gilles

**Comment by Gilmor49** [comment]
Une dernière petite question:
Pour un utilisateur Post-Only comment puis-je lui afficher les zones supplémentaires en lecture seule?
Cdt, Gilles

**Comment by tsmr** [comment]
Bonjour. Malheureusement, ce n'est pas pris en charge par le plugin
