### ISSUE TITLE
Le type d'attente de s'affiche pas si l'on a choisi l'affichage "séparation verticale"

### ISSUE THREAD

**Issue by dhordelalay** [InfotelGLPI/moreticket#18]
^Bonjour,

Le type d'attente de s'affiche pas si l'on a choisi l'affichage "séparation verticale".
De plus, comme j'ai rendu quelques champs obligatoires, dont le type d'attente, impossible d'aller plus loin (message d'erreur + non validation de la demande).

GLPI 0.90.1 MoreTicket  1.2.1

**Comment by philippeplatiau** [comment]
Bonjour, je confirme, j'ai le même comportement avec GLPI 0.90.3 et MoreTicket 1.2.1

**Comment by jffroment** [comment]
J'ai également le même comportement avec GLPI 9.1.2 et MoreTicket 1.2.4
Cela se produit aussi si la disposition est en "vue classique".
Seule le disposition "Onglets sur la gauche" permet l'affichage des zones complémentaires.
Cela concerne les zones pour l'attente et la zone de justification de l'urgence.

**Comment by amma35** [comment]
Ce bug est corrigé en version 1.2.5.
La release est sortie.

**Comment by jffroment** [comment]
Je viens de tester cette release 1.2.5.
Je n'ai toujours pas accès aux zones complémentaires du plugin.
PS: j'ai vidé le cache des navigateurs, et essayé avec chrome et IE...

**Comment by amma35** [comment]
Je viens d'effectuer des nouveaux tests sur cette release, les 3 modes de disposition fonctionne.
Pouvez-vous activer le mode debug dans GLPI (Préférences > Principal > Utiliser GLPI en Mode = Oui) et vérifier dans l'interface du ticket, cliquez sur "See GLPI DEBUG" et vérifier que le plugin Moreticket est bien chargé avec la présence de ses mots dans Autoload "PluginMoreticketProfile", "PluginMoreticketConfig" ...

**Comment by jffroment** [comment]
Bonjour,

Merci pour vos réponses rapides, c’est très appréciable !
Je confirme que ça ne fonctionne pas malgré la présence des mots dans le debug AUTOLOAD.

Voici des copies d’écran avec le statut en attente et priorité très haute :

Merci pour tout ce que vous faites.

[cid:image002.jpg@01D2AFC0.572EEB40]




[cid:image004.jpg@01D2AFC0.572EEB40]

[Logo CHB signature mail]

Jean-François FROMENT
Service Informatique
Centre Hospitalier de BRIOUDE
2 Rue Michel de l’Hospital
BP 140
43100 BRIOUDE
Tel : 04.71.50.98.73
Mail : jffroment@ch-brioude.fr<mailto:jffroment@ch-brioude.fr>

P Afin de contribuer au respect de l'environnement, merci de n'imprimer ce message qu'en cas de nécessité

De : Amandine Manceau [mailto:notifications@github.com]
Envoyé : vendredi 7 avril 2017 15:18
À : InfotelGLPI/moreticket <moreticket@noreply.github.com>
Cc : Jean-François FROMENT <jffroment@ch-brioude.fr>; Comment <comment@noreply.github.com>
Objet : Re: [InfotelGLPI/moreticket] Le type d'attente de s'affiche pas si l'on a choisi l'affichage "séparation verticale" (#18)


Je viens d'effectuer des nouveaux tests sur cette release, les 3 modes de disposition fonctionne.
Pouvez-vous activer le mode debug dans GLPI (Préférences > Principal > Utiliser GLPI en Mode = Oui) et vérifier dans l'interface du ticket, cliquez sur "See GLPI DEBUG" et vérifier que le plugin Moreticket est bien chargé avec la présence de ses mots dans Autoload "PluginMoreticketProfile", "PluginMoreticketConfig" ...

**Comment by amma35** [comment]
Pouvez-vous me donner la configuration du plugin ?

**Comment by jffroment** [comment]
Voici notre config issue de la table glpi_plugin_moreticket_configs  :

`id`                                         : 1
`use_waiting`                           : 1
`use_solution`                          : 1
`close_informations`                 : 1
`solution_status`                      : {\"5\":\"1\"}
`waitingtype_mandatory`          : 1
`date_report_mandatory`          : 1
`solutiontype_mandatory`         : 0
`close_followup`                       : 0
`waitingreason_mandatory`      : 1
`urgency_justification`              : 1
`urgency_ids`                          : [\"5\"]

Merci

[Logo CHB signature mail]

Jean-François FROMENT
Service Informatique
Centre Hospitalier de BRIOUDE
2 Rue Michel de l’Hospital
BP 140
43100 BRIOUDE
Tel : 04.71.50.98.73
Mail : jffroment@ch-brioude.fr<mailto:jffroment@ch-brioude.fr>

P Afin de contribuer au respect de l'environnement, merci de n'imprimer ce message qu'en cas de nécessité

De : Amandine Manceau [mailto:notifications@github.com]
Envoyé : vendredi 14 avril 2017 08:32
À : InfotelGLPI/moreticket <moreticket@noreply.github.com>
Cc : Jean-François FROMENT <jffroment@ch-brioude.fr>; Comment <comment@noreply.github.com>
Objet : Re: [InfotelGLPI/moreticket] Le type d'attente de s'affiche pas si l'on a choisi l'affichage "séparation verticale" (#18)


Pouvez-vous me donner la configuration du plugin ?

**Comment by amma35** [comment]
Je n'arrive pas à reproduire votre bug.

Pouvez-vous me dire ce que vous avez dans la console et dans network en filtrant a "moreticket" comme dans l'image ci dessous ? 

![moreticket](https://cloud.githubusercontent.com/assets/15138371/25040136/e02d631e-2107-11e7-82ef-5774a47a166b.png)

**Comment by jffroment** [comment]
Par rapport à votre copie d’écran, il me manque moreticket.css

**Comment by jffroment** [comment]
Est-ce que je peux faire d'autres essais pour vous aider à debugger ?

**Comment by amma35** [comment]
Sans le chargement du fichier moreticket.css, c'est normal que vous ne voyez pas la mise en attente. 
La mise en attente fonctionne toujours avec le mode "Onglets sur la gauche" ? 
Car le chargement de ce fichier n'a aucune incidence sur le chargement de ce fichier.
Il faudrait dans un deuxième temps vérifier que ce fichier est bien présent dans glpi/plugins/moreticket/moreticket.css

**Comment by jffroment** [comment]
Le fichier moreticket.css  est bien présent dans le répertoire du plugin.

Je suis passé en mode « Onglets sur la gauche » , la justification de l’urgence ne fonctionne pas non plus.
Voici les seuls fichiers chargés :

moreticket.css
moreticket.js


[cid:image002.png@01D2BDDE.B8E6D290]

**Comment by amma35** [comment]
Vous indiquez plus haut que le fichier moreticket.css n'est pas chargé, il est donc bien chargé ? 
Par contre les images que vous inserez ne sont pas lisibles.

**Comment by jffroment** [comment]
Oui maintenant le fichier moreticket.css est bien chargé mais je n'ai plus les autres.

![image](https://cloud.githubusercontent.com/assets/26977642/25429929/f187cc2c-2a7a-11e7-8140-6796dbe773eb.png)

**Comment by amma35** [comment]
c'est normal, j'ai déjà selectionné le statut "En attente" c'est pour ça que j'ai plus de fichiers chargés que vous.
