### ISSUE TITLE
Petit bug à la résolution dans Moreticket 1.2.3 pour GLPI 9.1

### ISSUE THREAD

**Issue by sebfun** [InfotelGLPI/moreticket#28]
Bonjour
J'ai découvert un petit bug. Quand on créé un ticket qu'on le résout de suite depuis l'interface support, le texte de la résolution reste présent lorsque l'on réitère la même opération et ainsi de suite.

**Comment by amma35** [comment]
Bonjour,
Lors de la création du ticket en passant le statut à résolu, vous saisissez la description de la solution puis vous ajoutez le ticket. Et lors de la création  d'un nouveau ticket, en passant le statut à résolu vous retrouvez la dernière description de la solution.
C'est cette démarche que vous appliquez ?

**Comment by sebfun** [comment]
tout à fait

**Comment by amma35** [comment]
Je n'arrive pas à reproduire votre bug.
Quel navigateur utilisez-vous ?

**Comment by sebfun** [comment]
Firefox 49.0.1 et bientôt 0.2 car il me dit qu'il y a une mise à jour
Je suis sur Windows 7 Pro SP1 (32 bits)

**Comment by sebfun** [comment]
J'ai retesté ce matin en vidant le cache du navigateur je n'ai pas réussi à reproduire le problème...

**Comment by sebfun** [comment]
Je l'ai refait ce matin et cela a recommencé. Il me garde bien ce que j'ai déjà écrit dans la petite fenêtre de résolution exactement comme à une demande précédente

**Comment by sebfun** [comment]
Je viens de nouveau d'avoir le problème
Sur un ticket précédemment clôturé, j'ai saisi la phrase de clôture "désolé j'ai oublié de répondre : problème résolu" là c'est ok
pour un autre ticket que je n'ai pas clôturé ni mis en résolu mais simplement attribué
Il a automatiquement mis un suivi de résolution avec la phrase suivante "désolé j\'ai oublié de répondre : problème résolu" le slash a été ajouté alors que je ne l'avais pas mis.
Le nom du technicien n'apparaît pas, il n'y a pas de nom

Voilà ce que ça donne en copie d'écran : 
http://www.cjoint.com/c/FLDkUx3uJhk
