### ISSUE TITLE
envoi d'un mail même si Suivi par courriel mis sur "non"

### ISSUE THREAD

**Issue by sebfun** [InfotelGLPI/moreticket#29]
Bonjour
Dans GLPI 9.1, lorsque je créé un ticket et que je mets : 
- Demandeur suivi par mail non
- Attribué à suivi par mail non
- Statut : clos

Automatiquement je reçois quand même un mail de création de ticket avec dans le mail Statut clos
Normalement je ne devrais pas recevoir de mail en tant que technicien ni même en tant que demandeur si j'ai mis suivi par mail non

**Comment by tsmr** [comment]
Pas de rapport avec le plugin je pense.

**Comment by sebfun** [comment]
comment en être sûr vu que j'utilise bien la zone de champ permettant de faire une résolution / clôture dans la création d'un ticket ?

**Comment by amma35** [comment]
Le plugin Moreticket n'impacte pas l'envoi de notification.

**Comment by sebfun** [comment]
bonjour
Je pense avoir trouvé. En fait j'avais mis dans les notifications pour "New ticket" administrateur et technicien donc GLPI envoie un mail mais ce qui n'est pas normal c'est que cela envoie un mail même si on indique pas de suivi que ce soit pour le demandeur et pour le technicien
Du coup le plugin n'a effectivement rien à voir. 
Je clos ma demande
