### ISSUE TITLE
Insertion d'une zone de suivi

### ISSUE THREAD

**Issue by sebfun** [InfotelGLPI/moreticket#30]
Bonjour

J'ai pensé à l'idée de mettre une zone pour ajouter un suivi en même temps que l'on créé un ticket

Je m'explique. Si je suis au téléphone avec un utilisateur je saisis le ticket puis en  discutant je lui soumets une idée mais sans que le ticket ne soit résolu. 
Qu'en pensez-vous ?

**Comment by amma35** [comment]
Bonjour,

Oui effectivement cela pourrait être interressant.
A voir dans une prochaine release ou vous souhaitez via un developpement dedié.

**Comment by thiagopassamani** [comment]
You could add a follow-up with status waiting type, reason and postponement date to keep history?

**Comment by tsmr** [comment]
Old issue - i close
