### ISSUE TITLE
In version 9.1.1 GLPI does not work correctly plugin 1.2.3

### ISSUE THREAD

**Issue by gloomy-master** [InfotelGLPI/moreticket#31]
Good day.

In version 9.1.1 GLPI does not work correctly plugin 1.2.3. 

When working in the section «Processing ticket», via the "Task" if a transfer request in anticipation, does not appear to indicate additional fields: The reason deferred date, the waiting type.

At the same time if you go to the «Ticket» and there put on hold, additional fields appear.

Thank you.

**Comment by amma35** [comment]
Release create with the correction: https://github.com/InfotelGLPI/moreticket/releases/tag/1.2.4
