### ISSUE TITLE
rien ne s'affiche avec firefox

### ISSUE THREAD

**Issue by Edzilla2000** [InfotelGLPI/moreticket#32]
Dans GLPI 9.1.2 avec moreticket en 1.2.4, les champs supplémentaires ne s'affichent pas dans firefox, que ce soit les raisons de mise en attente ou de priorité haute.

Je n'ai pas de soucis avec chrome

**Comment by amma35** [comment]
Je viens de tester sous Firefox et Internet Explorer, les champs supplémentaires s'affichent.

Pouvez-vous vider votre cache et re-tester?

**Comment by Edzilla2000** [comment]
je viens de réessayer en vidant mon cache, en mode sans échec firefox, sur une autre machine, j'ai toujours le même soucis.

**Comment by Edzilla2000** [comment]
Bonjour, 
Avez-vous pu regarder ce qui pourrait poser le soucis? Je peux tout à fait faire des tests ou fournir des logs.
Je ne sais pas si ça peut avoir un rapport, mais nous utilisons GLPI avec une authentification Kerberos assurée par Apache.

**Comment by amma35** [comment]
Quelle disposition utilisez-vous ? 
Onglet sur la gauche, vue classique ou séparation verticale?

**Comment by Edzilla2000** [comment]
Bonjour, 
J'utilise la séparation verticale.

**Comment by amma35** [comment]
Bonjour,

Si vous avez toujours le soucis. Passer le plugin en version 1.2.6.

**Comment by Edzilla2000** [comment]
Effectivement, le souci est résolu.
Merci!
