### ISSUE TITLE
Pb de sortie de l'attente sur action automatique MoreticketWaitingTicket

### ISSUE THREAD

**Issue by hasop** [InfotelGLPI/moreticket#33]
version du plugin : 1.2.4
version GLPI : 9.1.1

2 comportements étranges constatés liés à l'action automatique MoreticketWaitingTicket :
- Lorsque le ticket passe directement de "Nouveau" à "En attente" (sans attribution préalable de technicien), l'action automatique repasse le ticket en "En cours attribué" une fois la date de report atteinte, alors qu'il n'y a pas de technicien attribué. Le ticket devrait alors revenir en "Nouveau" puisqu'il n'y a pas de technicien attribué.

- Lorsqu'il n'y a pas de date de report renseignée (possible si champ non obligatoire dans la conf), le ticket repasse directement en "En cours attribué" dés la prochaine exécution de l'action automatique. Sans date de report, le ticket ne devrait pas sortir de l'état "En attente".

**Comment by amma35** [comment]
Correction apportée pour le bug lorsqu'une date de report n'est pas renseignée, lors de l'action automatique le ticket reste avec le statut "En attente".
