### ISSUE TITLE
Problème de mise à jour des droits du profile

### ISSUE THREAD

**Issue by hasop** [InfotelGLPI/moreticket#35]
Dans GLPI 9.1.1 avec la v1.2.4, lorsque l'on coche tout les cases de droit dans un profile, la valeur de droit est mise à 3 en base. 
Cela ne semble pas suffisant pour que les données complémentaires (raison, type, date de report) soient prises en compte lors de la mise en attente d'un ticket.
Lorsque la valeur est mise à 127 directement en base, cela fonctionne.

**Comment by amma35** [comment]
Bonjour,

Je n'ai pas réussi a reproduire votre bug.
Le plugin moreticket a seulement les droits de lecture et mise à jour c'est pour ça que la valeur est à 3 ce qui est normal. 
Vous n'obtenez pas d'erreur lorsque vous mettez a jour un droit dans les fichiers de logs (glpi/files/_log/php-errors.log et sql-errors.log) ?

**Comment by hasop** [comment]
Bonjour,
Aucune erreur malheureusement dans les logs.Cela impactait tous nos gestionnaires avec un niveau de droit inférieur à admin.Je n'avais pas le problème avec mon compte admin, c'est pourquoi j'ai reporté la valeur en base.

      De : Amandine Manceau <notifications@github.com>
 À : InfotelGLPI/moreticket <moreticket@noreply.github.com> 
Cc : hasop <ngrehall@yahoo.fr>; Author <author@noreply.github.com>
 Envoyé le : Samedi 20 mai 2017 18h57
 Objet : Re: [InfotelGLPI/moreticket] Problème de mise à jour des droits du profile (#35)
   
Bonjour,Je n'ai pas réussi a reproduire votre bug.
Le plugin moreticket a seulement les droits de lecture et mise à jour c'est pour ça que la valeur est à 3 ce qui est normal.
Vous n'obtenez pas d'erreur lorsque vous mettez a jour un droit dans les fichiers de logs (glpi/files/_log/php-errors.log et sql-errors.log) ?—

**Comment by hasop** [comment]
Par contre, je ne me souviens plus de l’enchaînement, mais il est possible que j'ai tenté de mettre la version suivante.Puis, suite à une erreur avec cette version, j'ai fait un retour arrière.Est-ce que cela a pu avoir une incidence ?

      De : Amandine Manceau <notifications@github.com>
 À : InfotelGLPI/moreticket <moreticket@noreply.github.com> 
Cc : hasop <ngrehall@yahoo.fr>; Author <author@noreply.github.com>
 Envoyé le : Samedi 20 mai 2017 18h57
 Objet : Re: [InfotelGLPI/moreticket] Problème de mise à jour des droits du profile (#35)
   
Bonjour,Je n'ai pas réussi a reproduire votre bug.
Le plugin moreticket a seulement les droits de lecture et mise à jour c'est pour ça que la valeur est à 3 ce qui est normal.
Vous n'obtenez pas d'erreur lorsque vous mettez a jour un droit dans les fichiers de logs (glpi/files/_log/php-errors.log et sql-errors.log) ?—

**Comment by amma35** [comment]
La nouvelle version du plugin a des nouvelles fonctionnalitées donc c'est possible mais cela n'impacte pas les droits.
La nouvelle version doit fonctionner, nous l'avons essayé sur plusieurs instances. Il peut y avoir un problème de cache ou de conflit avec d'autes plugins.

**Comment by amma35** [comment]
Toujours le problème ? 
Sinon tester avec la version 1.2.6.
