### ISSUE TITLE
Afficher la saisie de solution lorsqu'on update un ticket

### ISSUE THREAD

**Issue by pippo571** [InfotelGLPI/moreticket#36]
Bonjour,

J'utilise ce plugin depuis peu et il m'est vraiment utile.

Mon seul problème est que la saisie de solution n'est disponible qu'à la création d'un nouveau ticket.

J'ai essayé de modifier :

../ajax/tickets.php on line 53 :

`if (isset($_POST['type'] && $_POST['type'] == 'add')  CHANGE EN  if (isset($_POST['type'] && $_POST['type'] == 'add' || $_POST['type'] == 'update')`

Le problème est que la saisie de solution s'affiche maintenant avec n'importe quel statut lorque j'update un ticket (au lieu de s'afficher à la sélection des statuts "clos" et "résolu"). La partie attente fonctionne toujours correctement. Lorsqu'on crée un nouveau ticket, tout fonctionne normalement aussi.

J'ai également modifié "../scripts/moreticket.js" :

` if (status_bloc != undefined && status_bloc.length != 0) {
                        status_bloc.parent().append(requester);

                        // ON DISPLAY : Display or hide waiting type
                        if ($("#moreticket_waiting_ticket") != undefined) {
                            // WAITING TICKET
                            if (status_bloc.val() == object.params.waiting) {
                                $("#moreticket_waiting_ticket").css({'display': 'block'});
                            } else {
                                $("#moreticket_waiting_ticket").css({'display': 'none'});
                            }
                            
                            //MODIFICATION  APPPORTEE
                            
                            // CLOSE TICKET
                            var show_solution = false;
                            if (object.params.solution_status != null && object.params.solution_status != '') {
                                $.each($.parseJSON(object.params.solution_status), function (index, val) {
                                    if (index == status_bloc.val()) {
                                        show_solution = true;
                                    }
                                });
                            }
                            if (show_solution && object.params.use_solution) {
                                $("#moreticket_close_ticket").css({'display': 'block'});
                            } else {
                                $("#moreticket_close_ticket").css({'display': 'none'});
                            }

                            // ONCHANGE : Display or hide waiting type
                            status_bloc.change(function () {
                                // WAITING TICKET
                                if (status_bloc.val() == object.params.waiting) {
                                    $("#moreticket_waiting_ticket").css({'display': 'block'});
                                } else {
                                    $("#moreticket_waiting_ticket").css({'display': 'none'});
                                }
                                
                                //MODIFICATION APPORTEE
                                
                                // CLOSE TICKET
                                var show_solution = false;
                                if (object.params.solution_status != null && object.params.solution_status != '') {
                                    $.each($.parseJSON(object.params.solution_status), function (index, val) {
                                        if (index == status_bloc.val()) {
                                            show_solution = true;
                                        }
                                    });
                                }
                                if (show_solution && object.params.use_solution) {
                                    $("#moreticket_close_ticket").css({'display': 'block'});
                                } else {
                                    $("#moreticket_close_ticket").css({'display': 'none'});
                                }
                            });
                        }
                    }
                }
            });
        }`

Malgrès mes modifications je n'ai toujours aucun résultats. Quelqu'un peut me dire ce que j'ai mal fait?

Est-ce prévu dans les prochaines versions?

Merci beaucoup

Pippo571

**Comment by amma35** [comment]
Cela n'est pas prévu pour les prochaines versions, car la solution est saisissable dans le traitement du ticket mais cela n'est pas possible lors de la création du ticket. 

Votre modification va varier selon la version du plugin que vous utilisez.
