### ISSUE TITLE
[GLPI 1.9.4] moreticket 1.2.6

### ISSUE THREAD

**Issue by sebfun** [InfotelGLPI/moreticket#38]
Bonjour

A la suite de ma maj en GLPI 1.9.3 puis 1.9.4 et enfin du plugin 1.2.6, je constate que des résolutions de tickets sont automatiquement insérés dans des tickets que je consulte en reprenant le texte de résolution d'un ancien ticket et que des "\" et des "rn" sont ajoutés à tout bout de champ.

Quand je regarde Historique des accès du tickets.
Le cadre de résolution est précédé du mot "Demandeur" au lieu d'afficher le nom 

Ci-joint une copie d'écran http://www.cjoint.com/c/GFtitLz7a2k

Navigateur utilisé Firefox 52.0.1

Merci d'avance

**Comment by amma35** [comment]
Bonjour,

Les caractères ajoutés est un bug du coeur de la version GLPI 9.1.3 : https://github.com/glpi-project/glpi/issues/1944

Je vais regarder pour le mot "Demandeur".

**Comment by sebfun** [comment]
bonjour
pourtant comme indiqué j'ai migré en GLPI 1.9.4 après la 3. il me semblait que ce bug était corrigé.

**Comment by sebfun** [comment]
Ce que j'ai oublié de préciser c'est que la réponse de résolution avec le cadre se sont ajoutés automatiquement, je n'ai pas fait de clic sur "Résolution" puis ajout du texte.
