### ISSUE TITLE
Plus de liste de tickets (avec ou sans filtre)

### ISSUE THREAD

**Issue by SupportInfoYanmar** [InfotelGLPI/moreticket#40]
GLPI 9.2 / MoreTickets 1.3.0

Dés l'activation du plugin, la liste des tickets est vide (avec ou sans filtre).

**Comment by amma35** [comment]
Have you errors in apache or glpi logs ?

**Comment by SupportInfoYanmar** [comment]
no error in apache logs but a lot of deprecated errors in glpi/_log/php-errors.log.

  ### Backtrace :
  inc/toolbox.class.php:478                          Toolbox::backtrace()
  inc/db.function.php:549                            Toolbox::deprecated()
  plugins/fields/setup.php:229                       TableExists()
  plugins/fields/setup.php:155                       plugin_fields_checkFiles()
  inc/plugin.class.php:145                           plugin_init_fields()
  inc/includes.php:118                               Plugin::load()
  front/document.send.php:37                         include()

**Comment by amma35** [comment]
The error is not related to the moreticket plugin.

In the sql-error.log file?

**Comment by SupportInfoYanmar** [comment]
Error: Column 'date_end_suspension' in on clause is ambiguous
  Backtrace :
  inc/search.class.php:918
  inc/search.class.php:98                            Search::constructDatas()
  inc/search.class.php:81                            Search::showList()
  front/ticket.php:49                                Search::show()

**Comment by SupportInfoYanmar** [comment]
i have a big sql request before (moretickets is in question), did you want it ?

**Comment by amma35** [comment]
Can you give me the other sql errors ?

**Comment by SupportInfoYanmar** [comment]
2017-11-03 10:17:04 [480@yanglpi]
  *** MySQL query error:
  SQL: SELECT \'dkik\' AS currentuser,
                        `glpi_tickets`.`id` AS `ITEM_0`,   `glpi_tickets`.`name` AS `ITEM_1`,
                        `glpi_tickets`.`id` AS `ITEM_1_id`,
                        `glpi_tickets`.`id` AS `ITEM_1_id`, `glpi_tickets`.`content` AS `ITEM_1_content`, `glpi_tickets`.`status` AS `ITEM_1_status`, `glpi_tickets`.`type` AS `ITEM_2`,  `glpi_tickets`.`status` AS `ITEM_3`,  `glpi_plugin_moreticket_waitingtypes_71c8d2e98ea40d92d47240c63715e68c`.`name` AS `ITEM_4`,  `glpi_plugin_moreticket_waitingtickets_f4042c42b5f8c11fb6b075fcdb2cbae0`.`date_report` AS `ITEM_5`,  `glpi_tickets`.`priority` AS `ITEM_6`,   GROUP_CONCAT(DISTINCT `glpi_users_a5e2026cbcb683e774f93a59e24a62a4`.`id` SEPARATOR \'$$##$$\')
                                       AS `ITEM_7`,
                           GROUP_CONCAT(DISTINCT CONCAT(`glpi_tickets_users_d1524bb2ea1d461ab90aed3b5f0e7e60`.`users_id`, \' \',
                                                        `glpi_tickets_users_d1524bb2ea1d461ab90aed3b5f0e7e60`.`alternative_email`)
                                                        SEPARATOR \'$$##$$\') AS `ITEM_7_2`,
                           `glpi_tickets`.`content` AS `ITEM_8`,   GROUP_CONCAT(DISTINCT `glpi_users_f201be21cd638ee780d08cba4ceff0d4`.`id` SEPARATOR \'$$##$$\')
                                       AS `ITEM_9`,
                           GROUP_CONCAT(DISTINCT CONCAT(`glpi_tickets_users_819efb92c8b927b345e489211ec8e43b`.`users_id`, \' \',
                                                        `glpi_tickets_users_819efb92c8b927b345e489211ec8e43b`.`alternative_email`)
                                                        SEPARATOR \'$$##$$\') AS `ITEM_9_2`,
                           `glpi_itilcategories`.`completename` AS `ITEM_10`,  `glpi_tickets`.`date` AS `ITEM_11`,  `glpi_tickets`.`time_to_resolve` AS `ITEM_12`,  `glpi_tickets`.`status` AS `ITEM_12_status`, `glpi_tickets`.`solvedate` AS `ITEM_13`,  `glpi_tickets`.`closedate` AS `ITEM_14`,  `glpi_slas_slas_tto_id_bb5aab1a526f6069c73375c529fafec7`.`name` AS `ITEM_15`,  `glpi_slas_slas_ttr_id_f3aab278f60e510b77ec99388d401d84`.`name` AS `ITEM_16`,  `glpi_ticketsatisfactions`.`satisfaction` AS `ITEM_17`,  `glpi_tickets`.`date_mod` AS `ITEM_18`,  `glpi_tickets`.`urgency` AS `ITEM_19`,  `glpi_tickets`.`impact` AS `ITEM_20`,  `glpi_tickets`.`id` AS id  FROM `glpi_tickets` LEFT JOIN `glpi_plugin_moreticket_waitingtickets`  AS `glpi_plugin_moreticket_waitingtickets_928ad4cb50a461d8789a01b2dc0b8343`
                                             ON (`glpi_tickets`.`id` = `glpi_plugin_moreticket_waitingtickets_928ad4cb50a461d8789a01b2dc0b8343`.`tickets_id`
                                                 AND (`glpi_plugin_moreticket_waitingtickets_928ad4cb50a461d8789a01b2dc0b8343`.`date_end_suspension` IS NULL) )LEFT JOIN `glpi_plugin_moreticket_waitingtypes`  AS `glpi_plugin_moreticket_waitingtypes_71c8d2e98ea40d92d47240c63715e68c`
                                          ON (`glpi_plugin_moreticket_waitingtickets_928ad4cb50a461d8789a01b2dc0b8343`.`plugin_moreticket_waitingtypes_id` = `glpi_plugin_moreticket_waitingtypes_71c8d2e98ea40d92d47240c63715e68c`.`id`
                                              ) LEFT JOIN `glpi_plugin_moreticket_waitingtickets`  AS `glpi_plugin_moreticket_waitingtickets_f4042c42b5f8c11fb6b075fcdb2cbae0`
                                             ON (`glpi_tickets`.`id` = `glpi_plugin_moreticket_waitingtickets_f4042c42b5f8c11fb6b075fcdb2cbae0`.`tickets_id`
                                                 AND `date_end_suspension` IS NULL ) LEFT JOIN `glpi_tickets_users`  AS `glpi_tickets_users_d1524bb2ea1d461ab90aed3b5f0e7e60`
                                             ON (`glpi_tickets`.`id` = `glpi_tickets_users_d1524bb2ea1d461ab90aed3b5f0e7e60`.`tickets_id`
                                                 AND `glpi_tickets_users_d1524bb2ea1d461ab90aed3b5f0e7e60`.`type` = 1 )LEFT JOIN `glpi_users`  AS `glpi_users_a5e2026cbcb683e774f93a59e24a62a4`
                                          ON (`glpi_tickets_users_d1524bb2ea1d461ab90aed3b5f0e7e60`.`users_id` = `glpi_users_a5e2026cbcb683e774f93a59e24a62a4`.`id`
                                              ) LEFT JOIN `glpi_tickets_users`  AS `glpi_tickets_users_819efb92c8b927b345e489211ec8e43b`
                                             ON (`glpi_tickets`.`id` = `glpi_tickets_users_819efb92c8b927b345e489211ec8e43b`.`tickets_id`
                                                 AND `glpi_tickets_users_819efb92c8b927b345e489211ec8e43b`.`type` = 2 )LEFT JOIN `glpi_users`  AS `glpi_users_f201be21cd638ee780d08cba4ceff0d4`
                                          ON (`glpi_tickets_users_819efb92c8b927b345e489211ec8e43b`.`users_id` = `glpi_users_f201be21cd638ee780d08cba4ceff0d4`.`id`
                                              )LEFT JOIN `glpi_itilcategories`
                                          ON (`glpi_tickets`.`itilcategories_id` = `glpi_itilcategories`.`id`
                                              )LEFT JOIN `glpi_slas`  AS `glpi_slas_slas_tto_id_bb5aab1a526f6069c73375c529fafec7`
                                          ON (`glpi_tickets`.`slas_tto_id` = `glpi_slas_slas_tto_id_bb5aab1a526f6069c73375c529fafec7`.`id`
                                              AND `glpi_slas_slas_tto_id_bb5aab1a526f6069c73375c529fafec7`.`type` = \'1\' )LEFT JOIN `glpi_slas`  AS `glpi_slas_slas_ttr_id_f3aab278f60e510b77ec99388d401d84`
                                          ON (`glpi_tickets`.`slas_ttr_id` = `glpi_slas_slas_ttr_id_f3aab278f60e510b77ec99388d401d84`.`id`
                                              AND `glpi_slas_slas_ttr_id_f3aab278f60e510b77ec99388d401d84`.`type` = \'0\' ) LEFT JOIN `glpi_ticketsatisfactions`
                                             ON (`glpi_tickets`.`id` = `glpi_ticketsatisfactions`.`tickets_id`
                                                 ) WHERE  `glpi_tickets`.`is_deleted` = \'0\'  AND  ( `glpi_tickets`.`entities_id` IN (\'0\')  )  AND (   `glpi_tickets`.`status` IN (\'1\') ) GROUP BY `glpi_tickets`.`id` ORDER BY ITEM_18 DESC
  Error: Column 'date_end_suspension' in on clause is ambiguous
  Backtrace :
  inc/search.class.php:918
  inc/search.class.php:98                            Search::constructDatas()
  inc/search.class.php:81                            Search::showList()
  front/ticket.php:49                                Search::show()

**Comment by amma35** [comment]
Can you test with this fix https://github.com/InfotelGLPI/moreticket/commit/838094a2ba3e5a97bed532a7cbe386f4d3369477

**Comment by SupportInfoYanmar** [comment]
did i need to replace 'NEWTABLE' with something ?

**Comment by amma35** [comment]
No, add it to `date_end_suspension`

**Comment by SupportInfoYanmar** [comment]
it's ok for me, great work ! see ya !

**Comment by amma35** [comment]
thank you for your tests
