### ISSUE TITLE
No registry in "Ticket suspension history" (Waiting tickets)

### ISSUE THREAD

**Issue by luisjosemachado** [InfotelGLPI/moreticket#41]
Hi
after changing the status to "pending" and register the waiting type  in the Moreticket plugin, there is no record displayed in the "Waiting ticket" tab.

GLPI 9.2.1
Moreticket 1.3.0
![waiting_ticket](https://user-images.githubusercontent.com/30940056/33339973-7db4302c-d459-11e7-9ebb-4c926f071d18.png)

Congratulations.

**Comment by luisjosemachado** [comment]
![waiting_ticket](https://user-images.githubusercontent.com/30940056/33339939-666a944c-d459-11e7-8102-0bac282119c1.png)

**Comment by amma35** [comment]
Have you errors in apache or glpi logs ?

**Comment by luisjosemachado** [comment]
hi amma35,
The fix on the file inc/waitingticket.class.php resolved this failure.
[https://github.com/InfotelGLPI/moreticket/commit/5dcb0bc5daec4cf37c88802babc028563b2bb0a3](url)

**Comment by amma35** [comment]
ok good note for a new release
