### ISSUE TITLE
[GLPI 9.1.4] Moreticket 1.2.6

### ISSUE THREAD

**Issue by sebfun** [InfotelGLPI/moreticket#44]
Bonjour
Dans GLPI 9.1.4, moreticket 1.2.6, j'ai constaté un bug quelque soit le navigateur.
Je m'explique : 
Quand je créé un nouveau ticket puis directement je le clos avec moreticket. Le contenu est reproduit dans un autre nouveau message (par forcément en utilisant more ticket)
Le champ demandeur qui clos le message est en anonyme et le texte qui renvoie à la ligne est remplacé par des CR LF (rn)

Exemple en image : 
https://www.cjoint.com/c/HCCijHNoiLk

**Comment by amma35** [comment]
Bonjour,

1. Le contenu est reproduit dans un autre nouveau message (par forcément en utilisant more ticket)
Pouvez-vous détailler votre problématique, je ne saisis pas le comportement que vous obtenez.

2. Le champ demandeur qui clos le message est en anonyme 
Problème corrigé dans la dernière version du plugin

3. Le texte qui renvoie à la ligne est remplacé par des CR LF (rn)
Vous utilisez quelle configuration, utilisation du riche text ? 

L'image n'est pas visible, vous pouvez directement insérer des images ici.

**Comment by sebfun** [comment]
Bonjour
1. Oui mais dès j'utilise le plugin. Le contenu d'une précédente résolution
est reportée dedans. Avec des cr lf
Par habitude je fais nouveau ticket et je le clos directement avec le
plugin.

2. Cela se produit uniquement lorsque je fais créer nouveau ticket et que
je vais voir s'il y a des suivis la automatiquement il y a un état marqué
résolu avec un demandeur anonyme

3. Je ne comprends pas ce que vous entendez par là Carine n'est pas
possible de choisir le texte enrichi directement dans les résolutions  avec
le plugin ?
Donc pour répondre à la question non je n'utilise pas le texte enrichi mais
je mets des retours à la ligne et donc lui il a interprété en remplaçant
les retours à la ligne

Le mer. 25 avr. 2018 à 11:11, Amandine Manceau <notifications@github.com> a
écrit :

**Comment by amma35** [comment]
Si je comprends bien, vous avez le même problème cette issue : https://github.com/InfotelGLPI/moreticket/issues/43 ?

**Comment by sebfun** [comment]
Bonjour
En effet c'est le même problème

Le mer. 25 avr. 2018 à 11:36, Amandine Manceau <notifications@github.com> a
écrit :

**Comment by amma35** [comment]
Duplicate #43

**Comment by sebfun** [comment]
Bonjour
Je reviens sur ce sujet car je ne peux pas faire d'upgrade du plugin sans changer la version de GLPI. En gros, je suis bloqué par la vêtusté de l'OS qui donc bloque l'upgrade d'Apache pour ensuite pouvoir upgrader GLPI puis more ticket. Je reste donc en GLPI 9.1.4
Est-il possible de corriger ce bug dans la version que j'utilise et si oui pouvez-vous m'indiquer les lignes à corriger ?
Merci d'avance

**Comment by keha35** [comment]
Bonjour,

Vous pouvez regarder au niveau de ce commit :
https://github.com/InfotelGLPI/moreticket/commit/a391e7cea2cfe6320376839f8148cbc05879030b

A priori les modifications ont résolu le problème.
