### ISSUE TITLE
glpi 0.90 master branch / more ticket master 

### ISSUE THREAD

**Issue by satyan01** [InfotelGLPI/moreticket#5]
Hello,

With this last version, the waiting windows does not appear and nothing happened.

If I try to save an error message telling you have to enter information before saving appears.

**Comment by tsmr** [comment]
Can you try with this correction ? 
https://github.com/InfotelGLPI/moreticket/commit/18d50d4970fffec6f0f8e19274667f56e95f4fbc

**Comment by satyan01** [comment]
I have tried this morning without positive result

**Comment by satyan01** [comment]
The issue is fixed. Thank you very much.
