### ISSUE TITLE
Fatal error: Uncaught Error: Call to undefined method CommonTreeDropdown::getSearchOptions

### ISSUE THREAD

**Issue by thiagopassamani** [InfotelGLPI/moreticket#53]
Error msg:
Fatal error: Uncaught Error: Call to undefined method CommonTreeDropdown::getSearchOptions() in /var/www/html/suporte/plugins/moreticket/inc/waitingtype.class.php:76 Stack trace: 
#0 /var/www/html/suporte/inc/commondbtm.class.php(3419): PluginMoreticketWaitingType->getSearchOptions() 
#1 /var/www/html/suporte/inc/search.class.php(5757): CommonDBTM->searchOptions() 
#2 /var/www/html/suporte/inc/search.class.php(5564): Search::getOptions('PluginMoreticke...', true) 
#3 /var/www/html/suporte/ajax/searchrow.php(50): Search::getCleanedOptions('PluginMoreticke...') 
#4 /var/www/html/suporte/inc/search.class.php(2179): include('/var/www/html/s...') 
#5 /var/www/html/suporte/inc/search.class.php(76): Search::showGenericSearch('PluginMoreticke...', Array) 
#6 /var/www/html/suporte/front/dropdown.common.php(46): Search::show('PluginMoreticke...')
#7 /var/www/html/suporte/plugins/moreticket/front/waitingtype.php(33): include('/var/www/html/s...')
#8 {main} thrown in /var/www/html/suporte/plugins/moreticket/inc/waitingtype.class.php on line 76

In file /glpi/plugins/moreticket/inc/waitingtype.class.php altered code to solved o erro :
[code:Original]
   function getSearchOptions() { 
      $tab = parent::getSearchOptions();
      return $tab;
   }
[/code

To: 
[code:Custom]
   function rawSearchOptions() { 
      $tab = parent::rawSearchOptions();
      return $tab;
   }
[/code]

Resolved fatal error.

**Comment by amma35** [comment]
it's normal this version isn't compatible for the moment with GLPI version 9.3.
