### ISSUE TITLE
PHP Notice: Undefined index: close_informations

### ISSUE THREAD

**Issue by jfg-fimac** [InfotelGLPI/moreticket#54]
Hi,

I have this error (Mode DEBUG) after install the plugin.

> PHP Notice: Undefined index: close_informations in /xxxx/xxxxx/glpi/plugins/moreticket/inc/config.class.php at line 320

I have retry installation two times and the problem is the same.

Thanks for your help ;)

_GLPI 9.3.0 
PHP 7.0.30_

**Comment by jfg-fimac** [comment]
```
316   /**
317    * @return mixed
318    */
319   function closeInformations() {
320      return $this->fields["close_informations"];
321   }
```

**Comment by amma35** [comment]
Hi,

SQL error during installation?

**Comment by jfg-fimac** [comment]
No SQL error during installation.

**Comment by amma35** [comment]
So from which version should we specify?

**Comment by jfg-fimac** [comment]
Oh sorry, 1.4.0 and this is the first installation for this plugin on my DB GLPI.

**Comment by jfg-fimac** [comment]
Now it's works fine !
Thanks you !!
