### ISSUE TITLE
Ajout de balises de notification

### ISSUE THREAD

**Issue by nicolasfassey** [InfotelGLPI/moreticket#55]
Serait-il possible d'ajouter des nouvelle balises de notification qui nous permettrais de récupérer les principaux champs du plugin par exemple : 
- Date de  report
- Type d'attente
- Raison

Etc ...
Ce serait vraiment très utile de pouvoir utiliser ces informations dans les notifications mail.

**Comment by tsmr** [comment]
Old issue - i close
