### ISSUE TITLE
Incorrect release 1.3.4 for glpi 9.2

### ISSUE THREAD

**Issue by BorisNovg** [InfotelGLPI/moreticket#56]
Incorrect release 1.3.4 for glpi 9.2

* Version of the plugin : 
1.3.4 (Version 1.3.4 released for GLPI >= 9.2 and < 9.3)

* Version of your GLPI : 
9.2.3

* Steps to reproduce (which actions have you made) :
Update release 1.3.3 to release 1.3.4 (https://github.com/InfotelGLPI/moreticket/releases/download/1.3.4/glpi-moreticket-1.3.4.tar.gz):
Change directory to .../glpi/plugins
Remove directory moreticket
wget https://github.com/InfotelGLPI/moreticket/releases/download/1.3.4/glpi-moreticket-1.3.4.tar.gz
tar -xvf glpi-moreticket-1.3.4.tar.gz

* Expected result :
Key "Upgrade" on Setup-Plugins page expected as enabled

* Actual result :
Key "Upgrade" on Setup-Plugins page not found, only text "This plugin requires GLPI > 9.3."

* URL of the page :
https://github.com/InfotelGLPI/moreticket/releases/tag/1.3.4

* Screenshot of the problem (if pertinent) :
![moreticket-1 3 4-glpi9 2 3-1](https://user-images.githubusercontent.com/39726474/43183711-cf7f73a2-8fee-11e8-98f4-b0c7ccbbb279.gif)

**Comment by keha35** [comment]
Hello, 
Thank you for the feedback.
I've update the release.
