### ISSUE TITLE
Le texte n'est pas affiché

### ISSUE THREAD

**Issue by jreicampos** [InfotelGLPI/moreticket#58]
Bonjour
Dans l'onglet Infos sur le ticket de fin, le texte saisi n'est pas affiché dans l'onglet Accompaniments. 
Seul le document joint est affiché.

**Comment by amma35** [comment]
Please use the template to create an issue : 
Dear GLPi user.

BEFORE SUBMITTING YOUR ISSUE, please make sure to read and follow these steps :

* Verify that your question has not already been asked
* Please use the below template.
* Delete this text before submiting your issue.

The Plugin team.

------------
* Version of the plugin : 


* Version of your GLPI : 


* Steps to reproduce (which actions have you made) :


* Expected result :

**Comment by jreicampos** [comment]
Sorry

Version plugin: 1.3.4
Version GLPI: 9.2.3 and 9.3
Step to reproduce:  After a closed ticket, access the End Ticket Information tab, fill in a text and a document, and click add.
Expected result: You are only viewing the attachment on the tracking tab. The text in earlier versions (I used 9.1.2) was also displayed.

Tks

**Comment by keha35** [comment]
Hello,

This fix resolve the problem,

Thanks for your repport.
