### ISSUE TITLE
White screen or error login (Link with AJAX)

### ISSUE THREAD

**Issue by jfg** [InfotelGLPI/moreticket#61]
Hi,

I have a big problem when i use GLPI with the plugin moreticket.
Many bug or white sreen when i create or modify a ticket.

I have update my GLPI and this is same...

Version of the plugin : 
**1.4.3**

Version of your GLPI : 
**GLPI 9.3.2**

Steps to reproduce (which actions have you made) :
Radomly when we use GLPI
Open a ticket ; Modidy a ticket ; Creat a solution in a ticket.

Expected result :
Just work !

Actual result :
White sreen or Acces denied or Login Screen

THANKS for your HELP.

**Comment by jfg-fimac** [comment]
Try to uninstall, clean, and install plugin = Same Bug.

**Comment by jfg-fimac** [comment]
Plugins list
--
fields               Name: Champs supplémentaires         Version: 1.8.1    
mod                  Name: GLPI Modifications             Version: 1.2.4     
moreticket           Name: More ticket                    Version: 1.4.3

**Comment by keha35** [comment]
Hi,

And have you try with only moreticket activated ?

**Comment by mate-infotel** [comment]
Hi,

Have you still this problem ?

**Comment by jfg** [comment]
I have no more access on this GLPI.
I close this HOLD issue.
