### ISSUE TITLE
Form does not appear [1.3.4]

### ISSUE THREAD

**Issue by juveboss** [InfotelGLPI/moreticket#62]
Dear GLPi user.

BEFORE SUBMITTING YOUR ISSUE, please make sure to read and follow these steps :

* Verify that your question has not already been asked
* Please use the below template.
* Delete this text before submiting your issue.

The Plugin team.

------------
* Version of the plugin : 
1.3.4

* Version of your GLPI : 
9.2.4
(google chrome)

* Steps to reproduce (which actions have you made) :
- Create a ticket
- Put on hold

* Expected result :
Form "pending" appears.

* Actual result :
I do not have the "pending" form that appears.
If I click on "save" the form appears.
If not, I have to empty my cache each time ...

* URL of the page :

* Screenshot of the problem (if pertinent) :

**Comment by keha35** [comment]
Hi, 

Which web browser did you use?
Have you some errors in glpi/files/_log/php-errors.log ?
Can you tell me which plugin you have ?

**Comment by juveboss** [comment]
Hi,

Google Chrome 71 x64 bits
GLPI 9.2
More ticket 1.3.3

No error in php-error.log...

Thanks

**Comment by keha35** [comment]
Hi,

You have juste this plugin no other plugins?
And can you try the release 1.3.4 of the plugin.
Can you check with the google chrome console if you have some js errors when you put an hold on a ticket?

**Comment by juveboss** [comment]
Hello,

Yes i have more plugin... 

Barcode	2.2.1	
Champs supplémentaires
Comportements	
Dashboard	
Formulaires	2.6.5	
FusionInventory	9.2+2.1	
Gestion des commandes	
GLPI Modifications	1.1.8	
Impression pdf	1.3.2	
Injection de fichiers	2.5.2	
More ticket	1.3.4	
Process Maker	3.4.5	
Purge de l'historique	1.3.0
Tableau de bord	0.9.5	
Ticket Cleaner	2.1.0	

sometimes the plugin works and some do not. We use all chrome latest version.

I check monday if i a error, thanks

**Comment by juveboss** [comment]
Hello, i have 1 error : 

<img width="972" alt="erreur-glpi" src="https://user-images.githubusercontent.com/31047406/53355094-8e46f200-3928-11e9-8a84-bde0acb93e2f.png">

On the picture:
It did not open, I did F5, and it opened.

Thanks

**Comment by juveboss** [comment]
Resolve in GLPI 9.4
