### ISSUE TITLE
6.4 version

### ISSUE THREAD

**Issue by Toinou2611** [InfotelGLPI/moreticket#63]
Hy,
it's possible to update as soon as possible your plugin for the 6.4 version
thanks a lot 
* Version of the plugin : 
6.3

* Version of your GLPI : 
6.4

* Steps to reproduce (which actions have you made) :
nothing

* Expected result :
update plugin

* Actual result :
nothing

**Comment by keha35** [comment]
Hi,

We already did the upgrade for the 9.4 version of glpi in the master branch.
We just haven't done any release. 
We are waiting the version 9.4 to be released.

If you realy want to use the plugin in 9.4 you can download the master branch but we don't recomand it.
It would be better to wait a release of the plugin.
