### ISSUE TITLE
[1.4.4] Several "Undefined index"

### ISSUE THREAD

**Issue by M-Falken** [InfotelGLPI/moreticket#64]
------------
* Version of the plugin : 1.4.4

* Version of your GLPI : 9.3.3
------------
Hello,
several  Undefined index

Some isset missing ?

  *** PHP Notice(8): Undefined index: reason
  Backtrace :
  plugins/moreticket/inc/waitingticket.class.php:550 
  plugins/moreticket/inc/ticket.class.php:147        PluginMoreticketWaitingTicket::preUpdateWaitingTicket()
  inc/plugin.class.php:1272                          PluginMoreticketTicket::beforeUpdate()
  inc/commondbtm.class.php:1347                      Plugin::doHook()
  plugins/moreticket/inc/tickettask.class.php:118    CommonDBTM->update()
  inc/plugin.class.php:1272                          PluginMoreticketTicketTask::beforeUpdate()
  inc/commondbtm.class.php:1347                      Plugin::doHook()
  front/commonitiltask.form.php:76                   CommonDBTM->update()
  front/tickettask.form.php:36                       include()
 
  *** PHP Notice(8): Undefined index: date_report
  Backtrace :
  plugins/moreticket/inc/waitingticket.class.php:551 
  plugins/moreticket/inc/ticket.class.php:147        PluginMoreticketWaitingTicket::preUpdateWaitingTicket()
  inc/plugin.class.php:1272                          PluginMoreticketTicket::beforeUpdate()
  inc/commondbtm.class.php:1347                      Plugin::doHook()
  plugins/moreticket/inc/tickettask.class.php:118    CommonDBTM->update()
  inc/plugin.class.php:1272                          PluginMoreticketTicketTask::beforeUpdate()
  inc/commondbtm.class.php:1347                      Plugin::doHook()
  front/commonitiltask.form.php:76                   CommonDBTM->update()
  front/tickettask.form.php:36                       include()
 
  *** PHP Notice(8): Undefined index: plugin_moreticket_waitingtypes_id
  Backtrace :
  plugins/moreticket/inc/waitingticket.class.php:552 
  plugins/moreticket/inc/ticket.class.php:147        PluginMoreticketWaitingTicket::preUpdateWaitingTicket()
  inc/plugin.class.php:1272                          PluginMoreticketTicket::beforeUpdate()
  inc/commondbtm.class.php:1347                      Plugin::doHook()
  plugins/moreticket/inc/tickettask.class.php:118    CommonDBTM->update()
  inc/plugin.class.php:1272                          PluginMoreticketTicketTask::beforeUpdate()
  inc/commondbtm.class.php:1347                      Plugin::doHook()
  front/commonitiltask.form.php:76                   CommonDBTM->update()
  front/tickettask.form.php:36                       include()

**Comment by Stoatwblr** [comment]
Also: 

  *** PHP Notice(8): Undefined index: reason
  Backtrace :
  plugins/moreticket/inc/ticketfollowup.class.php:71
  inc/plugin.class.php:1272                          PluginMoreticketTicketFollowup::beforeAdd()
  inc/commondbtm.class.php:1096                      Plugin::doHook()
  front/ticketfollowup.form.php:43                   CommonDBTM->add()
  {"user":"11@msslyz.mssl.ucl.ac.uk"}

[2019-01-24 15:21:39] glpiphplog.ERROR: Toolbox::userErrorHandlerNormal() in /usr/share/glpi/inc/toolbox.class.php line 657
  *** PHP Notice(8): Undefined index: date_report
  Backtrace :
  plugins/moreticket/inc/ticketfollowup.class.php:72
  inc/plugin.class.php:1272                          PluginMoreticketTicketFollowup::beforeAdd()
  inc/commondbtm.class.php:1096                      Plugin::doHook()
  front/ticketfollowup.form.php:43                   CommonDBTM->add()
  {"user":"11@msslyz.mssl.ucl.ac.uk","mem_usage":"0.000\", 4.85Mio)"}
[2019-01-24 15:21:39] glpiphplog.ERROR: Toolbox::userErrorHandlerNormal() in /usr/share/glpi/inc/toolbox.class.php line 657
 
 *** PHP Notice(8): Undefined index: plugin_moreticket_waitingtypes_id
  Backtrace :
  plugins/moreticket/inc/ticketfollowup.class.php:73
  inc/plugin.class.php:1272                          PluginMoreticketTicketFollowup::beforeAdd()
  inc/commondbtm.class.php:1096                      Plugin::doHook()
  front/ticketfollowup.form.php:43                   CommonDBTM->add()
  {"user":"11@msslyz.mssl.ucl.ac.uk","mem_usage":"0.000\", 4.85Mio)"}

2019-01-24 15:21:39 [11@msslyz.mssl.ucl.ac.uk]
  Backtrace :
  inc/toolbox.class.php:562                          Toolbox::backtrace()
  inc/commondbtm.class.php:315                       Toolbox::deprecated()
  plugins/projectbridge/inc/entity.class.php:29      CommonDBTM->getFromDBByQuery()
  plugins/projectbridge/hook.php:393                 PluginProjectbridgeEntity->getContractId()
  inc/plugin.class.php:1272                          plugin_projectbridge_ticket_update()
  inc/commondbtm.class.php:1347                      Plugin::doHook()
  plugins/moreticket/inc/ticketfollowup.class.php:76 CommonDBTM->update()
  inc/plugin.class.php:1272                          PluginMoreticketTicketFollowup::beforeAdd()
  inc/commondbtm.class.php:1096                      Plugin::doHook()
  front/ticketfollowup.form.php:43                   CommonDBTM->add()

2019-01-24 15:21:41 [11@msslyz.mssl.ucl.ac.uk]
  Backtrace :
  inc/toolbox.class.php:562                          Toolbox::backtrace()
  inc/ticketfollowup.class.php:839                   Toolbox::deprecated()
  inc/ticketfollowup.class.php:209                   TicketFollowup->showSummary()
  inc/commonglpi.class.php:485                       TicketFollowup::displayTabContentForItem()
  ajax/common.tabs.php:92                            CommonGLPI::displayStandardTab()

**Comment by Stoatwblr** [comment]
Still there in 9.4 / 1.5.0

**Comment by mate-infotel** [comment]
Hi.

To help you to resolve your issue I need more information.

Can you describe actions you've done before you get these errors messages ?

**Comment by Stoatwblr** [comment]
Are you trying to be funny? If so, you're not.

These are a well known error directly resulting from sloppy coding.

You can fix them trivially using isset() tests - as is done throughout GLPI in many places and even within your own plugin.

Better use of "lint" tests would find these missed tests before users reported them in the wild.

**Comment by PVTGoesen** [comment]
Hi,
we had the same problems and several other in  9.4 / 1.5.0 https://github.com/InfotelGLPI/moreticket/issues/74

But after I deleted the /inc folder and copying it from the master branch, it works fine.

**Comment by M-Falken** [comment]
Ok now glpi 10.0.7 more ticket 1.71
