### ISSUE TITLE
If "Waiting type" is mandatory, "Reason" shouldn't necessarily be

### ISSUE THREAD

**Issue by nbriche** [InfotelGLPI/moreticket#7]
Usually, the waiting type is enough ("Insufficient details", "User callback for validation", etc), there's no need to type a variation in the "Reason" field.  But I can't seem to set "Reason" as non-mandatory, even though a mandatory waiting type is set.

Unless I'm not using that field correctly?

**Comment by tsmr** [comment]
No by default the reaseon is always mandatory (must develop this fetature)

**Comment by satyan01** [comment]
with form plugin when the forms is created we can't use more ticket because the ticket is pending without reason. 

Or, we are waiting for compliance approval.

Please add reason mandatory option to permit no
