### ISSUE TITLE
Ajouter un suivi lors de la clôture à la création du ticket

### ISSUE THREAD

**Issue by Synairgis** [InfotelGLPI/moreticket#71]
Bonjour,

Lorsqu'on veut ajouter un suivi de clôture à la création d'un ticket, la solution n'est jamais enregistré, il y a un message d'erreur à la place.

![image](https://user-images.githubusercontent.com/38703996/53598682-60a1b900-3b73-11e9-9d7b-b2f2f05d698a.png)

Test réalisé avec les versions 1.4.4 et 1.4.5 du plugin sur GLPI 9.3.2 et 9.3.3

Merci

**Comment by mate-infotel** [comment]
Bonjour.

Que voulez-vous dire par "ajouter un suivi de cloture" à la "création d'un ticket" ?

Vous voulez dire que vous créez un ticket avec un status clos ?

**Comment by Synairgis** [comment]
Bonjour,
Oui en effet, je veux créer un nouveau ticket avec un statut clos.
Lorsque j'essaie de faire cette action j'ai le message d'erreur mentionné plus haut.

Merci

**Comment by Synairgis** [comment]
Bonjour,
Après l'application du patch, la solution s'ajoute maintenant au ticket. ce qui est normal, cependant le message d'erreur s'affiche toujours.
![image](https://user-images.githubusercontent.com/38703996/57400485-98dffc00-71a1-11e9-9aa8-5712828ab3e5.png)

Aussi, lorsqu'on change de langue, le plugin ne réagit plus.
Il faut aller dans les paramètres du plugin, faire sauvegarder pour que ceux soient prise en compte

Merci
