### ISSUE TITLE
GLPI 9.4.1.1 Bug when ticket reload

### ISSUE THREAD

**Issue by zoriax** [InfotelGLPI/moreticket#72]
Hi everone,

We encounter a strange bug with moreticket. When I create a new ticket, I choose a category or a user, when page reloads, I was sometime redirefted to plugins/moreticket/ajax/ticket.php

This issue appears reandomly.

Thanks for your help

**Comment by ales-infotel** [comment]
Hi,
have you still have the problem?

**Comment by zoriax** [comment]
Hi,

Now it seems to be solved. For me you can close this case !
