### ISSUE TITLE
Problem with last release package

### ISSUE THREAD

**Issue by Wolvverine** [InfotelGLPI/moreticket#73]
Last release package don have "moreticket" directory as root directory in package.
Is problem with automatic instalation:
..downloading plugin 'moreticket' from 'https://github.com/InfotelGLPI/moreticket/releases/download/1.5.0/glpi-moreticket.1.5.0.tar.gz'
..extracting plugin '/tmp/glpi-moreticket.1.5.0.tar.gz'
chown: /var/www/plugins/moreticket: No such file or directory

**Comment by mate-infotel** [comment]
Hi.

I edit the release and it's ok now.
