### ISSUE TITLE
Bug sur new option in followup : ticket waiting => ticket is pending

### ISSUE THREAD

**Issue by rlamotte-png** [InfotelGLPI/moreticket#79]
Bonjour sur l'ecran de suivi j'ai l'option ticket en attente qui est duppliquée:

![image](https://user-images.githubusercontent.com/54978951/64415611-f162cf80-d095-11e9-8b6e-915d817cfc65.png)

* Version of the plugin : 1.5.1
* Version of your GLPI : 9.4.2

**Comment by keha35** [comment]
Bonjour,

C'est un problème de cache je pense.
Si vous faite un CTRL + F5 est-ce que le problème réapparaît?

Cordialement.

**Comment by rlamotte-png** [comment]
Bonjour.
aprés un  Ctrl + F5  + vidage de l'historique, cela fonctionne, par contre aléatoirement si je reviens sur le ticket j'ai de nouveau l'option ticket en attente en double.
ça le fait également en navigation privée

![image](https://user-images.githubusercontent.com/54978951/64418564-861bfc00-d09b-11e9-9bbe-0abb61bae5ff.png)
