### ISSUE TITLE
Plugin does not work with mobile access

### ISSUE THREAD

**Issue by Phorta** [InfotelGLPI/moreticket#82]
* Version of the plugin : 1.5.1

* Version of your GLPI : 9.4.2

* Steps to reproduce (which actions have you made) :When accessing the ticket by a mobile phone and placing the pending status, the more ticket plugin fields do not appear to place the reason or date.
When accessing a mobile phone a ticket that status is pending and has already been filled the more ticket plugin fields with the reasons, type and date. does not appear the waiting ticket tab

* Expected result :That because it is html responsive the plugin works normally on mobile accesses.
Most technicians access GLPI by mobile device

* Actual result :

* URL of the page :

* Screenshot of the problem (if pertinent) :

![image](https://user-images.githubusercontent.com/30396674/68399726-9e6ccd80-0155-11ea-9c02-89dfcec0a538.png)

![image](https://user-images.githubusercontent.com/30396674/68399748-a62c7200-0155-11ea-961a-e1164ec34b11.png)

**Comment by gguib** [comment]
hi,

I reproduced your use case by adding to a pending ticket a moreticket status and its working well for a responsive html expecting result. Can you show me the same ticket on a laptop responsive html case please ? 

Regards 


![image](https://user-images.githubusercontent.com/56250594/71617489-a5471800-2bbb-11ea-9c79-e1b42189b224.png)


![image](https://user-images.githubusercontent.com/56250594/71617503-b001ad00-2bbb-11ea-9a21-8a6d0cb6e1d6.png)

![image](https://user-images.githubusercontent.com/56250594/71617522-bee85f80-2bbb-11ea-8390-28045338e876.png)

**Comment by tsmr** [comment]
Old issue - i close
