### ISSUE TITLE
Ticket en attente dans un suivi de ticket par défaut en attente

### ISSUE THREAD

**Issue by mab18** [InfotelGLPI/moreticket#83]
* Version of the plugin : 
More ticket 1.5.1
* Version of your GLPI : 
9.4.4

* Steps to reproduce (which actions have you made) :
Activer "Ticket en attente dans un suivi de ticket par défaut", l'option de saisie de mise en attente s'affiche alors dans la saisie d'une tâche, mais elle est en attente par défaut. Si cette option n'est pas activée, la saisie de mise en attente dans la tâche n'est pas accessible.

* Expected result :
Quand la saisie de mise en attente est activée sur les tâches/suivis, elle ne devrait pas être par défaut activée.
Ou alors, il faudrait une option pour indiquer qu'on veut afficher cette possibilité dans les suivi/tâches (ce que j'en attend) ET une option pour la mettre par défaut ou pas.

**Comment by gguib** [comment]
Bonjour,

Je tag votre demande comme potentielle fonctionnalité à venir dans une prochain release.

**Comment by tsmr** [comment]
Old issue - i close
