### ISSUE TITLE
Type d'attente - affichage liste

### ISSUE THREAD

**Issue by WilfriedJaconelli** [InfotelGLPI/moreticket#84]
Dans l'affichage liste des tickets, le champ Type d'attente ne se met pas ajour lorsqu'on modifie le type d'attente.

Exemple, je met un ticket en attente avec comme type d'attente "Technicien", le type d'attente dans l'affichage liste sera bien "Technicien". Je reviens dans le ticket et change le type d'attente par "Utilisateur" dans l'affichage liste, le type d'attente est toujours "Technicien".

Je dois changer le statut du ticket par "En cours" par exemple puis revenir à "En attente" pour que le type d'attente se mette à jour dans la liste.

**Comment by gguib** [comment]
Bonjour,

Quelles versions de glpi et de moreticket utilisés vous ?

**Comment by WilfriedJaconelli** [comment]
Bonjour,

GLPI : 9.4.3

Moreticket : 1.5.1

Merci pour votre support.

**Comment by gguib** [comment]
Bonjour,

Je viens de tester la même manip et ça fonctionne bien de mon côté.
Avez-vous récemment vider le cache de votre navigateur ou celui de votre serveur Glpi ?

**Comment by tsmr** [comment]
Old issue - i close
