### ISSUE TITLE
Add New followUP changed status on notification

### ISSUE THREAD

**Issue by lsaille** [InfotelGLPI/moreticket#85]
Dear GLPi dev.

------------
* Version of the plugin : 1.5.1
* Version of your GLPI : 9.4.5
* Steps to reproduce (which actions have you made) :
Add follow with changed status "wait"

* Expected result :
Add notification new statut 
* Actual result :
the task is Added on ticket but without notification with status modified
* URL of the page :

* Screenshot of the problem (if pertinent) :

**Comment by tsmr** [comment]
Old issue -  i close
