### ISSUE TITLE
error when activating plugin 1.6 in glpi 9.5.1

### ISSUE THREAD

**Issue by mdesfawes** [InfotelGLPI/moreticket#87]
Dear GLPi user.

BEFORE SUBMITTING YOUR ISSUE, please make sure to read and follow these steps :

* Verify that your question has not already been asked
* Please use the below template.
* Delete this text before submiting your issue.

The Plugin team.

------------
* Version of the plugin : 

1.6
* Version of your GLPI : 

9.5.1
* Steps to reproduce (which actions have you made) :
activate plugin in marketplace

* Expected result :
must be activated

* Actual result :
error : PHP Notice (8): Undefined index: use_duration_solution in /var/www/html/glpi/ict/marketplace/moreticket/inc/config.class.php at line 359

* URL of the page :

* Screenshot of the problem (if pertinent) :

**Comment by Bevox** [comment]
- Version of the plugin :
1.6

- Version of your GLPI :
9.5.1

- Steps to reproduce (which actions have you made) :
activate plugin in plugins section -> error500 page

- Expected result :
must be activated

Actual result :
error 500 on my browser.

- URL of the page :
https://support.xxxx.fr/front/plugin.form.php

Screenshot of the problem (if pertinent) :
![error500glpi](https://user-images.githubusercontent.com/25570562/89281825-eec47d80-d64a-11ea-8d35-4ba077606598.png)

**Comment by mdesfawes** [comment]
after installing new version : 
php notice (8) undefined index : use_duration_solution in /var /www/html/glpi/ict/marketplace/moreticket/inc/config.class at line 359

**Comment by Bevox** [comment]
Okay! Thanks for you reply.
I found the problem. I had the folder moreticket in glpi/plugins and in glpi/marketplace.
There was conflict. After deleting one of two, I could setup moreticket properly.

**Comment by mdesfawes** [comment]
Thanks for the update

After installing new version, I have this error when activating

PHP Notice (8): Undefined index: use_duration_solution in /var/www/html/glpi/ict/marketplace/moreticket/inc/config.class.php at line 359


i don’t have a folder more ticket in plugins directory

thanks and Best regards

Michel

**Comment by keha35** [comment]
Hi,

we have desabled the plugin from the marketplace for now.
It will be enabled for the next release.

Br
