### ISSUE TITLE
Add default option option for Ticket Waiting

### ISSUE THREAD

**Issue by raregtp** [InfotelGLPI/moreticket#88]
Dear GLPi user.

BEFORE SUBMITTING YOUR ISSUE, please make sure to read and follow these steps :

* Verify that your question has not already been asked
* Please use the below template.
* Delete this text before submiting your issue.

The Plugin team.

------------
* Version of the plugin : 1.6.0

* Version of your GLPI : 9.5.1

* Steps to reproduce (which actions have you made) : Add a follow-up to a ticket with the Ticket waiting option "Use the option ticket waiting in ticket follow-up"

* Expected result : Option defaults to 'on' when enabled

* Actual result : Prefer to have this option available in a ticket but defaulted 'off' as normally follow-ups will not require using the ticket waiting function.

* URL of the page :

* Screenshot of the problem (if pertinent) : 

![image](https://user-images.githubusercontent.com/16689744/89565935-e6a04580-d7e4-11ea-8c81-aebcc37706b9.png)

**Comment by epigraphe** [comment]
Will it work in GLPI 10?

**Comment by epigraphe** [comment]
> Will it work in GLPI 10?

I meant will this patch work? Or what is needed to enable this option by default in glpi 10?

**Comment by tsmr** [comment]
Old issue - i close
