### ISSUE TITLE
Time not showed in task ticket

### ISSUE THREAD

**Issue by magaiverpr** [InfotelGLPI/moreticket#89]
------------
* Version of the plugin : 1.6.0

* Version of your GLPI : 9.5.1

* Steps to reproduce (which actions have you made) : Just turn ON the plugin

* Expected result :
Show time of the task

* Actual result :
Dont show the time

* URL of the page :

* Screenshot of the problem (if pertinent) :

![image](https://user-images.githubusercontent.com/10533823/91349249-6bb2c500-e7bb-11ea-8ee8-afc3125549fd.png)

![image](https://user-images.githubusercontent.com/10533823/91349331-88e79380-e7bb-11ea-9d42-be5133ae2c9b.png)

**Comment by magaiverpr** [comment]
Sorry, found that is a checkbox in profile to show this information

**Comment by hcimadomo** [comment]
Hello,
please can you precise what is the parameter in profile for this , please ?
BR
