### ISSUE TITLE
affichage ticket depuis site support

### ISSUE THREAD

**Issue by sebfun** [InfotelGLPI/moreticket#9]
Bonjour
dans GLPI 0.90 et more ticket 1.2.1, j'ai pu remarquer que via le site support quand on choisi le statut résolu puis qu'on choisi un type de gabarit de solution. Dans la description de la solution (toujours depuis le gabarit) s'il y a des retours de chariot, lorsque l'on valide le formulaire et que GLPI nous l'affiche on peut voir dans le champ "Traitement du ticket" que les retours de chariot sont remplacés par "rn"
Sinon ce plugin est très bien et on gagne du temps

**Comment by tsmr** [comment]
Bonjour ceci a été corrigé et sera intégré à la version 1.2.2

https://github.com/InfotelGLPI/moreticket/commit/f5f7b141e515e6ca518bad4b48ec7c5ce729f42e

**Comment by sebfun** [comment]
merci
