### ISSUE TITLE
Waiting type status does not change

### ISSUE THREAD

**Issue by pedrox120** [InfotelGLPI/moreticket#90]
Dear GLPi user.

BEFORE SUBMITTING YOUR ISSUE, please make sure to read and follow these steps :

* Verify that your question has not already been asked
* Please use the below template.
* Delete this text before submiting your issue.

The Plugin team.

------------
* Version of the plugin : 1.5.1

* Version of your GLPI : 9.4.5

* Steps to reproduce (which actions have you made) :
Assign a ticket the status "Pending" and assign it a "waiting type", then change the status to "Processing", then change the status to "Pending" and assign a different "waiting time". These steps simulate a status change on the ticket.

* Expected result :
- As long as the ticket is in any other state than "Pending" the "Plugins - Waiting type" field must be blank.
- If the ticket has several changes such as passing status "Pending" -> "Processing" -> "Pending" the Waiting type must always be the last one assigned

* Actual result :
- The ticket always shows the "Waiting type" in whatever state the ticket is
- The ticket does not show the current "Waiting type" of the ticket after passing several state changes. Example: "Pending" -> "Processing" -> "Pending"
- In my case, when changing the status of the ticket "Pending" -> "Processing" the following error occurs in the log "sql-errors.log"
[2020-09-06 15:51:44] glpisqllog.ERROR: DBmysql::query() in /var/www/html/glpi/inc/dbmysql.class.php line 188
  *** MySQL query error:
  SQL: SELECT * FROM `glpi_plugin_moreticket_waitingtickets` WHERE `tickets_id` = '123' AND (((`date_end_suspension` IS NULL) OR (`date_end_suspension` = '')))
  Error: Incorrect DATETIME value: ''
  Backtrace :
  inc/dbmysqliterator.class.php:95                   
  inc/dbmysql.class.php:580                          DBmysqlIterator->execute()
  inc/commondbtm.class.php:525                       DBmysql->request()
  plugins/moreticket/inc/waitingticket.class.php:578 CommonDBTM->find()
  plugins/moreticket/inc/ticket.class.php:161        PluginMoreticketWaitingTicket::postUpdateWaitingTicket()
  inc/plugin.class.php:1112                          PluginMoreticketTicket::afterUpdate()
  inc/commondbtm.class.php:1443                      Plugin::doHook()
  front/ticket.form.php:72                           CommonDBTM->update()
  {"user":"7@glpiupgrade.quanam.cl"} 

* URL of the page :

* Screenshot of the problem (if pertinent) :
![error_waiting_type_1](https://user-images.githubusercontent.com/34429155/92333969-fa4b0000-f05f-11ea-85a4-cc599c5e1406.png)
![error_waiting_type_2](https://user-images.githubusercontent.com/34429155/92333970-fdde8700-f05f-11ea-9d16-bfceaa1fe88d.png)

**Comment by gguib** [comment]
Hi, 

I tried to reproduce your bug but for me it worked with Glpi 9.4.7 & moreticket 1.5.1.
No SQL errors log and the change of status is working well.
Doesn't it just work with this ticket in particular or for others too ?

**Comment by tprudent0803** [comment]
Hi,

I'm in GLPI 9.5.2 and I have the same problem. When I put a waiting status on a ticket, it works fine, but, when the ticket change of status, the filed waiting status keep the information and I have ticket solved with a waiting status. 

I haven't look if I have the same SQL error.

If someone have a solution.

Thx

**Comment by SilvaFernando** [comment]
Hi, 

we have some kind of solution for this bug.

**Comment by tsmr** [comment]
Old issue - use GLPI10 - i close
