### ISSUE TITLE
Unable to activate Plugin : PHP Error (1): Class PluginMoreticketTicket contains 1 abstract method (CommonITILObject::getItemLinkClass)

### ISSUE THREAD

**Issue by Dead-Red** [InfotelGLPI/moreticket#92]
* Version of the plugin : 1.6.0

* Version of your GLPI : 9.5.3

* Steps to reproduce (which actions have you made) :

After update my GLPI from 9.5.2 to 9.5.3 i wanted to activate back the plugin More ticket
(this plugin was activated in previous version 9.5.2 as well)

* Expected result : When I wanted to activate the Plugin after the GLPI's update.

* Actual result : This notification in red : 

PHP Error (1): Class PluginMoreticketTicket contains 1 abstract method and must therefore be declared abstract or implement the remaining methods 
(CommonITILObject::getItemLinkClass) in /var/www/html/glpi/plugins/moreticket/inc/ticket.class.php at line 0

And if you reload page : Unable to use GLPI (all pages are blank)

And to permit to reuse the glpi, it was necessary to desactivate the plugin from command line : 

/var/www/html/glpi/console glpi:plugin:deactivate moreticket

(Same problem if i uninstall and install back)

* URL of the page :

* Screenshot of the problem (if pertinent) :

Thank's a lot

**Comment by tsmr** [comment]
https://github.com/InfotelGLPI/moreticket/releases/tag/1.6.1

**Comment by Dead-Red** [comment]
Thank's you, but is not available in marketplace :( The latest version in marketplace was 1.6.0

**Comment by Dead-Red** [comment]
Thank's a lot ! The last package is better :D
