### ISSUE TITLE
GLPI 9.5.5 / More Ticket 1.6.1 - Mise en Attente ne fonctionne plus comme dans les versions précédentes

### ISSUE THREAD

**Issue by Acs2i** [InfotelGLPI/moreticket#94]
Bonjour

Ci dessous le détail d'un souci que nous rencontrons avec le plugin MoreTicket sur notre recette en env. de Développpement

Merci d'avance de l'attention portée à ce message

Acs2i 

------------
* Version of the plugin : 
![image](https://user-images.githubusercontent.com/41065966/117827434-44c8f000-b271-11eb-9b21-4f3ef42aa26f.png)

* Version of your GLPI : 
GLPI 9.5.5 Copyright (C) 2015-2021 Teclib' and contributors
FusionInventory 9.5+3.0 - Copyleft © 2010-2019 by FusionInventory Team

* Steps to reproduce (which actions have you made) :
- Création d'un ticket
- retour sur ce ticket pour mise en attente, la liste des options de mise en attente n'apparait plus comme dans les versions précécentes

* Expected result :
en version précédente, ci dessous l'écran qui été affiché
![image](https://user-images.githubusercontent.com/41065966/117827897-a5f0c380-b271-11eb-9715-8ef03c64b71a.png)

* Actual result :
Lors de la mise en attente, rien ne se passe 
![image](https://user-images.githubusercontent.com/41065966/117827976-ba34c080-b271-11eb-9b67-d37839040986.png)

**Comment by Acs2i** [comment]
Hi,
The plugin was installed in the folder glpi/marketplace
I uninstalled it and reinstalled it in the glpi/plugins folder and it works!
I thought that the folder glpi/marketplace replaced glpi/plugins

**Comment by M-Falken** [comment]
Yes the folders are both active at this time.
But More Ticket is not already compatible with the Marketplace so you must still use the standard folder for it now.
Simply if you can see a plugin in the marketplace discover list, so it use the marketplace folder.
And if you look more ticket is not yet in the list
Regards

**Comment by Acs2i** [comment]
Thank you for this clarification.
