### ISSUE TITLE
Info in ticket is not the same as in ticket view

### ISSUE THREAD

**Issue by danicouso** [InfotelGLPI/moreticket#96]
Info in ticket is not the same as in ticket view

Ticket view
![imagen](https://user-images.githubusercontent.com/75984175/143471466-915d724d-ca25-4090-acaf-6deccb8465b7.png)

Plugin ticket info
![imagen](https://user-images.githubusercontent.com/75984175/143471687-1c138621-0d7f-435c-b1e3-ce4c89f658e8.png)

What more information do you need? Thanks

**Comment by tsmr** [comment]
Old issue - use GLPI10 - i close
