### ISSUE TITLE
No solution when close a new ticket

### ISSUE THREAD

**Issue by Captain-Adam** [InfotelGLPI/moreticket#97]
Dear GLPi user.

BEFORE SUBMITTING YOUR ISSUE, please make sure to read and follow these steps :

* Verify that your question has not already been asked
* Please use the below template.
* Delete this text before submiting your issue.

The Plugin team.

------------
* Version of the plugin : 1.6.1

* Version of your GLPI : 9.5.5

* Steps to reproduce (which actions have you made) :

      - Open new ticket
      - Change status "new" to "closed"
      - Fill in the fields of the solution
      - Save changes

* Expected result : closure of the new ticket with the addition of the solution.

* Actual result : Ticket closed but no solution

* URL of the page :

* Screenshot of the problem (if pertinent) :

![image](https://user-images.githubusercontent.com/13540283/144861993-bddec070-ff49-4224-b3f4-7001b38fa97e.png)

**Comment by tsmr** [comment]
Old issue - use GLPI10 - i close
