### ISSUE TITLE
Error unsignrd_keys

### ISSUE THREAD

**Issue by JeanBuchweitz** [InfotelGLPI/moreticket#99]
[root@JMBAWB glpihqi]# php bin/console glpi:migration:unsigned_keys
PHP Warning: PluginPhpsamlConfig::showForm() declaration must be compatible with CommonDBTM::showForm($ID, array $options = Array) in /var/www/html/glpihqi/plugins/phpsaml/inc/config.class .php on line 53
Found 2 primary/foreign key columns using signed integers.
Do you wish to continue? [yes/no] yes
Migration of column "glpi_plugin_moreticket_urgencytickets.tickets_id" cannot be done because it is a CONSTRAINT reference "glpi_plugin_moreticket_urgencytickets_ibfk_1" from table "glpi_plugin_moreticket_urgencytickets.tickets_id".
The migration of column "glpi_tickets.id" cannot be done because it is a CONSTRAINT reference "glpi_plugin_moreticket_urgencytickets_ibfk_1" from table "glpi_plugin_moreticket_urgencytickets.tickets_id".
 2/2 [==============================] 100%
Errors occurred during migration.

**Comment by YannickBarone** [comment]
Hi,
I get the same error qith my GLPI 10.0.2 server.
Any news about this issue ?
Thanks,

**Comment by tsmr** [comment]
You can launch on your mysql before : 

```
ALTER TABLE `glpi_plugin_moreticket_notificationtickets` DROP FOREIGN KEY glpi_plugin_moreticket_notificationtickets_ibfk_1;
ALTER TABLE `glpi_plugin_moreticket_urgencytickets` DROP FOREIGN KEY glpi_plugin_moreticket_urgencytickets_ibfk_1;
```
